- hosts: master
  become: yes
  become_user: vagrant
  gather_facts: false
  tasks:
    - name: install kubernetes dashboard
      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml

    - name: add service accounts required for kubernetes dashboard
      shell: kubectl apply -f /vagrant/kube-cluster/required_files/k8s-dashboard-serviceaccount.yaml

    - name: get secrets token name
      shell: kubectl describe sa dashboard-admin -n kubernetes-dashboard
      register: token_name

    # - name: print token_name
    #   debug: var=token_name.stdout_lines[5]

    - name: get secret
      shell: kubectl describe secret "{{ token_name.stdout_lines[5][21:] }}" -n kubernetes-dashboard
      register: secret

    # - name: print secret
    #   debug: var=secret.stdout_lines[12][12:]

    - name: print secret to a file
      shell: echo "{{ secret.stdout_lines[12][12:] }}" >> /home/vagrant/secret