- hosts: masters
  become: yes
  gather_facts: false
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=10.10.10.20 >> /home/vagrant/cluster_initialized.txt

    - name: create .kube directory
      file:
        path: /home/vagrant/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant
        mode: 0600

    - name: add nodeip for kubelet
      lineinfile:
        path: /etc/sysconfig/kubelet
        regexp: '^KUBELET_EXTRA_ARGS='
        line: KUBELET_EXTRA_ARGS=--node-ip={{ hostvars[inventory_hostname]['ansible_host'] }}

    - name: reload systemd daemon && restart kubelet
      systemd:
        state: restarted
        daemon_reload: yes
        name: kubelet

    - name: get flannel yml file
      get_url:
        url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
        dest: /home/vagrant/kube-flannel.yml
    
    - name: install flannel Pod network
      become: yes
      become_user: vagrant
      shell: kubectl apply -f /home/vagrant/kube-flannel.yml

    - name: install flannel Pod network
      become: yes
      become_user: vagrant
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    
  
    # - name: print debug
    #   debug: var=hostvars
            #  var=hostvars[inventory_hostname]["ansible_host"]

    # - name: print debug
    #   debug: 
    #     msg: IP ADDRESS - {{ hostvars[inventory_hostname]['ansible_host'] }}

