- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:
    # - name: Print the join command
    #   debug: var=hostvars['master'].join_command

    - name: join cluster
      shell: "{{ hostvars['master'].join_command }}"

    - name: add nodeip for kubelet
      lineinfile:
        path: /etc/sysconfig/kubelet
        regexp: '^KUBELET_EXTRA_ARGS='
        line: KUBELET_EXTRA_ARGS=--node-ip={{ hostvars[inventory_hostname]['ansible_host'] }}

    - name: reload systemd daemon && restart kubelet
      systemd:
        state: restarted
        daemon_reload: yes
        name: kubelet