---
apiVersion: v1
kind: Service
metadata:
  name: lendy-app-service-np
  labels:
    name: lendy-app-service-np
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 5000
      nodePort: 32121
      protocol: TCP
      name: http
  selector:
    app: lendy-app