---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-np
  labels:
    name: nginx-service-np
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8080
      nodePort: 30000
      protocol: TCP
      name: http
  selector:
    app: nginx